///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace hoclieu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the hoclieuRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("45603024-c765-4da1-862e-9ee56605b11e")]
    public partial class hoclieuRepository : RepoGenBaseFolder
    {
        static hoclieuRepository instance = new hoclieuRepository();
        hoclieuRepositoryFolders.HọcLiệuSachMềmAppFolder _họcliệusachmềm;
        hoclieuRepositoryFolders.StartAppFolder _start;

        /// <summary>
        /// Gets the singleton class instance representing the hoclieuRepository element repository.
        /// </summary>
        [RepositoryFolder("45603024-c765-4da1-862e-9ee56605b11e")]
        public static hoclieuRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public hoclieuRepository() 
            : base("hoclieuRepository", "/", null, 0, false, "45603024-c765-4da1-862e-9ee56605b11e", ".\\RepositoryImages\\hoclieuRepository45603024.rximgres")
        {
            _họcliệusachmềm = new hoclieuRepositoryFolders.HọcLiệuSachMềmAppFolder(this);
            _start = new hoclieuRepositoryFolders.StartAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("45603024-c765-4da1-862e-9ee56605b11e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềm folder.
        /// </summary>
        [RepositoryFolder("934f8b75-8e8e-4e93-a27c-ce48dcf022ed")]
        public virtual hoclieuRepositoryFolders.HọcLiệuSachMềmAppFolder HọcLiệuSachMềm
        {
            get { return _họcliệusachmềm; }
        }

        /// <summary>
        /// The Start folder.
        /// </summary>
        [RepositoryFolder("e51a89c9-4473-4182-80dd-1aea0fa424bd")]
        public virtual hoclieuRepositoryFolders.StartAppFolder Start
        {
            get { return _start; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class hoclieuRepositoryFolders
    {
        /// <summary>
        /// The HọcLiệuSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("934f8b75-8e8e-4e93-a27c-ce48dcf022ed")]
        public partial class HọcLiệuSachMềmAppFolder : RepoGenBaseFolder
        {
            hoclieuRepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder _httpshoclieusachmemvnquestionset;
            RepoItemInfo _giaobaitậpInfo;
            RepoItemInfo _javascriptvoid0Info;
            RepoItemInfo _somespantagInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềm  folder.
            /// </summary>
            public HọcLiệuSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềm", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "934f8b75-8e8e-4e93-a27c-ce48dcf022ed", "")
            {
                _httpshoclieusachmemvnquestionset = new hoclieuRepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder(this);
                _giaobaitậpInfo = new RepoItemInfo(this, "GiaoBaiTập", "body/tag[@tagname='app-root']/div[2]//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']/span[@innertext='Giao bài tập']", 30000, null, "8fc00295-4ee2-4d24-bd59-b761db83f5c4");
                _javascriptvoid0Info = new RepoItemInfo(this, "JavascriptVoid0", "body/tag[@tagname='app-root']/div[2]/div//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']", 30000, null, "a796d099-8479-4564-bb55-082cfbc5fbb3");
                _somespantagInfo = new RepoItemInfo(this, "SomeSpanTag", ".//div[#'createAssignmentModal']/div/div/div/?/?/span[@innertext='×']", 30000, null, "31cd04c6-856e-4761-8d0e-4b94fdab3aa8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("934f8b75-8e8e-4e93-a27c-ce48dcf022ed")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("934f8b75-8e8e-4e93-a27c-ce48dcf022ed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GiaoBaiTập item.
            /// </summary>
            [RepositoryItem("8fc00295-4ee2-4d24-bd59-b761db83f5c4")]
            public virtual Ranorex.SpanTag GiaoBaiTập
            {
                get
                {
                    return _giaobaitậpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GiaoBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("8fc00295-4ee2-4d24-bd59-b761db83f5c4")]
            public virtual RepoItemInfo GiaoBaiTậpInfo
            {
                get
                {
                    return _giaobaitậpInfo;
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item.
            /// </summary>
            [RepositoryItem("a796d099-8479-4564-bb55-082cfbc5fbb3")]
            public virtual Ranorex.ATag JavascriptVoid0
            {
                get
                {
                    return _javascriptvoid0Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JavascriptVoid0 item info.
            /// </summary>
            [RepositoryItemInfo("a796d099-8479-4564-bb55-082cfbc5fbb3")]
            public virtual RepoItemInfo JavascriptVoid0Info
            {
                get
                {
                    return _javascriptvoid0Info;
                }
            }

            /// <summary>
            /// The SomeSpanTag item.
            /// </summary>
            [RepositoryItem("31cd04c6-856e-4761-8d0e-4b94fdab3aa8")]
            public virtual Ranorex.SpanTag SomeSpanTag
            {
                get
                {
                    return _somespantagInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SomeSpanTag item info.
            /// </summary>
            [RepositoryItemInfo("31cd04c6-856e-4761-8d0e-4b94fdab3aa8")]
            public virtual RepoItemInfo SomeSpanTagInfo
            {
                get
                {
                    return _somespantagInfo;
                }
            }

            /// <summary>
            /// The HttpsHoclieuSachmemVnQuestionSet folder.
            /// </summary>
            [RepositoryFolder("38a76503-3ed8-4ac8-a263-8c18993a8d1d")]
            public virtual hoclieuRepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder HttpsHoclieuSachmemVnQuestionSet
            {
                get { return _httpshoclieusachmemvnquestionset; }
            }
        }

        /// <summary>
        /// The HttpsHoclieuSachmemVnQuestionSetFolder folder.
        /// </summary>
        [RepositoryFolder("38a76503-3ed8-4ac8-a263-8c18993a8d1d")]
        public partial class HttpsHoclieuSachmemVnQuestionSetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _submitInfo;
            RepoItemInfo _trườngnaykhongđượcđểtrốngInfo;
            RepoItemInfo _ngselectcontainerInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _nginputInfo;
            RepoItemInfo _ngoptionngoptionmarkedInfo;
            RepoItemInfo _numberInfo;
            RepoItemInfo _number1Info;
            RepoItemInfo _text1Info;
            RepoItemInfo _text2Info;
            RepoItemInfo _trườngnaykhongđượcđểtrống1Info;
            RepoItemInfo _đongInfo;
            RepoItemInfo _ngarrowwrapperInfo;
            RepoItemInfo _tiếnganhInfo;

            /// <summary>
            /// Creates a new HttpsHoclieuSachmemVnQuestionSet  folder.
            /// </summary>
            public HttpsHoclieuSachmemVnQuestionSetFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsHoclieuSachmemVnQuestionSet", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview']", parentFolder, 30000, null, false, "38a76503-3ed8-4ac8-a263-8c18993a8d1d", "")
            {
                _submitInfo = new RepoItemInfo(this, "Submit", "?/?/input[@type='submit']", 30000, null, "da3af32a-bd59-4ead-b583-155e63dae48c");
                _trườngnaykhongđượcđểtrốngInfo = new RepoItemInfo(this, "TrườngNayKhongĐượcĐểTrống", "div[1]/div[3]/div[@innertext~'^Trường\\ này\\ không\\ được\\ để\\ ']", 30000, null, "fd2c36bf-9728-48be-9508-f3453c085e7c");
                _ngselectcontainerInfo = new RepoItemInfo(this, "NgSelectContainer", "div[1]/div[3]/tag[@tagname='ng-select']/div", 30000, null, "1eb94612-d7d2-4ce6-bc62-9b242822da51");
                _textInfo = new RepoItemInfo(this, "Text", "div[1]/div[2]/input[@type='text']", 30000, null, "460d94c0-dfdc-48ed-81b8-1d8d15d39fdf");
                _nginputInfo = new RepoItemInfo(this, "NgInput", "div[1]/div[3]/tag[@tagname='ng-select']/div/div/div[2]", 30000, null, "6e8fcc4d-040c-4318-9721-2e4fc3009882");
                _ngoptionngoptionmarkedInfo = new RepoItemInfo(this, "NgOptionNgOptionMarked", "div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div[1]", 30000, null, "bfad51cf-cc63-4291-bf27-be94eea9c0ac");
                _numberInfo = new RepoItemInfo(this, "Number", "div[1]/div[6]/input[@type='number']", 30000, null, "c14988c6-1029-4703-8749-b8bcd42a56cf");
                _number1Info = new RepoItemInfo(this, "Number1", "div[1]/div[7]/input[@type='number']", 30000, null, "9206f8f7-d9ab-4f20-96e8-16672caec63b");
                _text1Info = new RepoItemInfo(this, "Text1", "div[1]/div[10]/div[2]//table/tbody/tr[2]/?/?/input[@type='text']", 30000, null, "48d3ec78-4165-49d8-a695-0727fd196cc5");
                _text2Info = new RepoItemInfo(this, "Text2", "div[1]/div[10]/div[2]//table/tbody/tr[2]/?/?/input[@value='49']", 30000, null, "9578d64a-efa2-4512-9024-4c9833451709");
                _trườngnaykhongđượcđểtrống1Info = new RepoItemInfo(this, "TrườngNayKhongĐượcĐểTrống1", "div[1]/div[10]/?/?/div[@innertext~'^Trường\\ này\\ không\\ được\\ để\\ ']", 30000, null, "15fdce01-0894-4418-94dc-64c4b66d7ec8");
                _đongInfo = new RepoItemInfo(this, "Đong", "?/?/button[@innertext='Đóng']", 30000, null, "5750579c-53c7-4cf8-9c53-ae0ea9f1474e");
                _ngarrowwrapperInfo = new RepoItemInfo(this, "NgArrowWrapper", "div[1]/div[3]//span", 30000, null, "1e4858db-ee36-44c3-bb40-b138c08e3ffa");
                _tiếnganhInfo = new RepoItemInfo(this, "TiếngAnh", "div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/?/?/span[@innertext='Tiếng Anh']", 30000, null, "87a6239f-4e91-43dd-b97d-592859e17bf1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("38a76503-3ed8-4ac8-a263-8c18993a8d1d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("38a76503-3ed8-4ac8-a263-8c18993a8d1d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("da3af32a-bd59-4ead-b583-155e63dae48c")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("da3af32a-bd59-4ead-b583-155e63dae48c")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The TrườngNayKhongĐượcĐểTrống item.
            /// </summary>
            [RepositoryItem("fd2c36bf-9728-48be-9508-f3453c085e7c")]
            public virtual Ranorex.DivTag TrườngNayKhongĐượcĐểTrống
            {
                get
                {
                    return _trườngnaykhongđượcđểtrốngInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TrườngNayKhongĐượcĐểTrống item info.
            /// </summary>
            [RepositoryItemInfo("fd2c36bf-9728-48be-9508-f3453c085e7c")]
            public virtual RepoItemInfo TrườngNayKhongĐượcĐểTrốngInfo
            {
                get
                {
                    return _trườngnaykhongđượcđểtrốngInfo;
                }
            }

            /// <summary>
            /// The NgSelectContainer item.
            /// </summary>
            [RepositoryItem("1eb94612-d7d2-4ce6-bc62-9b242822da51")]
            public virtual Ranorex.DivTag NgSelectContainer
            {
                get
                {
                    return _ngselectcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgSelectContainer item info.
            /// </summary>
            [RepositoryItemInfo("1eb94612-d7d2-4ce6-bc62-9b242822da51")]
            public virtual RepoItemInfo NgSelectContainerInfo
            {
                get
                {
                    return _ngselectcontainerInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("460d94c0-dfdc-48ed-81b8-1d8d15d39fdf")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("460d94c0-dfdc-48ed-81b8-1d8d15d39fdf")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The NgInput item.
            /// </summary>
            [RepositoryItem("6e8fcc4d-040c-4318-9721-2e4fc3009882")]
            public virtual Ranorex.DivTag NgInput
            {
                get
                {
                    return _nginputInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgInput item info.
            /// </summary>
            [RepositoryItemInfo("6e8fcc4d-040c-4318-9721-2e4fc3009882")]
            public virtual RepoItemInfo NgInputInfo
            {
                get
                {
                    return _nginputInfo;
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item.
            /// </summary>
            [RepositoryItem("bfad51cf-cc63-4291-bf27-be94eea9c0ac")]
            public virtual Ranorex.DivTag NgOptionNgOptionMarked
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item info.
            /// </summary>
            [RepositoryItemInfo("bfad51cf-cc63-4291-bf27-be94eea9c0ac")]
            public virtual RepoItemInfo NgOptionNgOptionMarkedInfo
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo;
                }
            }

            /// <summary>
            /// The Number item.
            /// </summary>
            [RepositoryItem("c14988c6-1029-4703-8749-b8bcd42a56cf")]
            public virtual Ranorex.InputTag Number
            {
                get
                {
                    return _numberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number item info.
            /// </summary>
            [RepositoryItemInfo("c14988c6-1029-4703-8749-b8bcd42a56cf")]
            public virtual RepoItemInfo NumberInfo
            {
                get
                {
                    return _numberInfo;
                }
            }

            /// <summary>
            /// The Number1 item.
            /// </summary>
            [RepositoryItem("9206f8f7-d9ab-4f20-96e8-16672caec63b")]
            public virtual Ranorex.InputTag Number1
            {
                get
                {
                    return _number1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number1 item info.
            /// </summary>
            [RepositoryItemInfo("9206f8f7-d9ab-4f20-96e8-16672caec63b")]
            public virtual RepoItemInfo Number1Info
            {
                get
                {
                    return _number1Info;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("48d3ec78-4165-49d8-a695-0727fd196cc5")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("48d3ec78-4165-49d8-a695-0727fd196cc5")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("9578d64a-efa2-4512-9024-4c9833451709")]
            public virtual Ranorex.InputTag Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("9578d64a-efa2-4512-9024-4c9833451709")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The TrườngNayKhongĐượcĐểTrống1 item.
            /// </summary>
            [RepositoryItem("15fdce01-0894-4418-94dc-64c4b66d7ec8")]
            public virtual Ranorex.DivTag TrườngNayKhongĐượcĐểTrống1
            {
                get
                {
                    return _trườngnaykhongđượcđểtrống1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TrườngNayKhongĐượcĐểTrống1 item info.
            /// </summary>
            [RepositoryItemInfo("15fdce01-0894-4418-94dc-64c4b66d7ec8")]
            public virtual RepoItemInfo TrườngNayKhongĐượcĐểTrống1Info
            {
                get
                {
                    return _trườngnaykhongđượcđểtrống1Info;
                }
            }

            /// <summary>
            /// The Đong item.
            /// </summary>
            [RepositoryItem("5750579c-53c7-4cf8-9c53-ae0ea9f1474e")]
            public virtual Ranorex.ButtonTag Đong
            {
                get
                {
                    return _đongInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Đong item info.
            /// </summary>
            [RepositoryItemInfo("5750579c-53c7-4cf8-9c53-ae0ea9f1474e")]
            public virtual RepoItemInfo ĐongInfo
            {
                get
                {
                    return _đongInfo;
                }
            }

            /// <summary>
            /// The NgArrowWrapper item.
            /// </summary>
            [RepositoryItem("1e4858db-ee36-44c3-bb40-b138c08e3ffa")]
            public virtual Ranorex.SpanTag NgArrowWrapper
            {
                get
                {
                    return _ngarrowwrapperInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The NgArrowWrapper item info.
            /// </summary>
            [RepositoryItemInfo("1e4858db-ee36-44c3-bb40-b138c08e3ffa")]
            public virtual RepoItemInfo NgArrowWrapperInfo
            {
                get
                {
                    return _ngarrowwrapperInfo;
                }
            }

            /// <summary>
            /// The TiếngAnh item.
            /// </summary>
            [RepositoryItem("87a6239f-4e91-43dd-b97d-592859e17bf1")]
            public virtual Ranorex.SpanTag TiếngAnh
            {
                get
                {
                    return _tiếnganhInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TiếngAnh item info.
            /// </summary>
            [RepositoryItemInfo("87a6239f-4e91-43dd-b97d-592859e17bf1")]
            public virtual RepoItemInfo TiếngAnhInfo
            {
                get
                {
                    return _tiếnganhInfo;
                }
            }
        }

        /// <summary>
        /// The StartAppFolder folder.
        /// </summary>
        [RepositoryFolder("e51a89c9-4473-4182-80dd-1aea0fa424bd")]
        public partial class StartAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _groupitemsInfo;

            /// <summary>
            /// Creates a new Start  folder.
            /// </summary>
            public StartAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Start", "/winapp[@appid='App' and @name='Start']", parentFolder, 30000, null, true, "e51a89c9-4473-4182-80dd-1aea0fa424bd", "")
            {
                _groupitemsInfo = new RepoItemInfo(this, "GroupItems", "?/?/list[@automationid='groupItems']", 30000, null, "8f9a2271-2ad5-439a-afd2-f2115c9cbcb4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e51a89c9-4473-4182-80dd-1aea0fa424bd")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e51a89c9-4473-4182-80dd-1aea0fa424bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GroupItems item.
            /// </summary>
            [RepositoryItem("8f9a2271-2ad5-439a-afd2-f2115c9cbcb4")]
            public virtual Ranorex.List GroupItems
            {
                get
                {
                    return _groupitemsInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The GroupItems item info.
            /// </summary>
            [RepositoryItemInfo("8f9a2271-2ad5-439a-afd2-f2115c9cbcb4")]
            public virtual RepoItemInfo GroupItemsInfo
            {
                get
                {
                    return _groupitemsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
