///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace hoclieu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("c335378c-a570-4345-af7b-658e0eefc072", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the hoclieuRepository repository.
        /// </summary>
        public static hoclieuRepository repo = hoclieuRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview", "Chrome", "", false, true, false, false, false, true);
            Delay.Milliseconds(11780);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.JavascriptVoid0' at 33;27.", repo.HọcLiệuSachMềm.JavascriptVoid0Info, new RecordItemIndex(1));
            repo.HọcLiệuSachMềm.JavascriptVoid0.Click("33;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Submit' at 32;24.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.SubmitInfo, new RecordItemIndex(2));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Submit.Click("32;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TrườngNayKhongĐượcĐểTrống'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TrườngNayKhongĐượcĐểTrốngInfo, new RecordItemIndex(3));
            Validate.Exists(repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TrườngNayKhongĐượcĐểTrốngInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Đong' at 27;17.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.ĐongInfo, new RecordItemIndex(4));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Đong.Click("27;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
