///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace hoclieu
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("63faad5e-a851-40e9-a929-6a130e4f1846", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the hoclieuRepository repository.
        /// </summary>
        public static hoclieuRepository repo = hoclieuRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.GiaoBaiTập' at 25;15.", repo.HọcLiệuSachMềm.GiaoBaiTậpInfo, new RecordItemIndex(0));
            repo.HọcLiệuSachMềm.GiaoBaiTập.Click("25;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgArrowWrapper' at 9;16.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgArrowWrapperInfo, new RecordItemIndex(1));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NgArrowWrapper.Click("9;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TiếngAnh' at 48;9.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TiếngAnhInfo, new RecordItemIndex(2));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TiếngAnh.Click("48;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number' at 251;29.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(4));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number.Click("251;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad6}{NumPad0}' with focus on 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(5));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number.PressKeys("{NumPad6}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1' at 237;13.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1Info, new RecordItemIndex(6));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1.Click("237;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1Info, new RecordItemIndex(7));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Number1.PressKeys("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(8));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1' at 42;25.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1Info, new RecordItemIndex(9));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1.Click("42;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}' with focus on 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1Info, new RecordItemIndex(10));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1.PressKeys("{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}{NumPad5}' with focus on 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1Info, new RecordItemIndex(11));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Text1.PressKeys("{NumPad2}{NumPad5}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Submit' at 26;9.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.SubmitInfo, new RecordItemIndex(12));
            repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.Submit.Click("26;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TrườngNayKhongĐượcĐểTrống1'.", repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TrườngNayKhongĐượcĐểTrống1Info, new RecordItemIndex(13));
            Validate.Exists(repo.HọcLiệuSachMềm.HttpsHoclieuSachmemVnQuestionSet.TrườngNayKhongĐượcĐểTrống1Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
